version: "3.8"

services:
  codegen:
    container_name: kansai-lovers-codegen
    build:
      context: ./swagger
    volumes:
      - ./swagger/openapi.yml:/app/openapi.yml
      - codegen-generate-server:/app/generate/server
      - ./src/@types/generate:/app/generate/client

  mock:
    container_name: kansai-lovers-mock
    image: node:16.1.0-alpine
    working_dir: /app
    volumes:
      - codegen-generate-server:/app
    command: yarn start
    depends_on:
      - codegen

  nginx:
    container_name: kansai-lovers-nginx
    image: nginx:1.21.3-alpine
    ports:
      - 8080:8080
    volumes:
      - ./nginx/my.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - mock

volumes:
  codegen-generate-server:
  codegen-generate-client:
