/* tslint:disable */
/* eslint-disable */
/**
 * Skillme API Document
 * This is a Skillme API Document.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hirokikondo86@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001
     */
    id: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001
     */
    github_name: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001
     */
    avatar_url: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001
     */
    url: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001
     */
    join_date: any;
    /**
     * 
     * @type {Array&lt;Chip&gt;}
     * @memberof InlineResponse2001
     */
    chips: any | null;
}
