/* tslint:disable */
/* eslint-disable */
/**
 * Skillme API Document
 * This is a Skillme API Document.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hirokikondo86@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Member
 * @export
 * @interface Member
 */
export interface Member {
  /**
   *
   * @type {string}
   * @memberof Member
   */
  login: any;
  /**
   *
   * @type {number}
   * @memberof Member
   */
  id: any;
  /**
   *
   * @type {string}
   * @memberof Member
   */
  avatar_url: any;
  /**
   *
   * @type {string}
   * @memberof Member
   */
  url: any;
  /**
   *
   * @type {string}
   * @memberof Member
   */
  join_date: any;
  /**
   *
   * @type {Array&lt;Tag&gt;}
   * @memberof Member
   */
  tags?: any;
}
