/* tslint:disable */
/* eslint-disable */
/**
 * Skillme API Document
 * This is a Skillme API Document.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hirokikondo86@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MessageStamps
 */
export interface MessageStamps {
    /**
     * 
     * @type {number}
     * @memberof MessageStamps
     */
    good_count: any;
    /**
     * 
     * @type {number}
     * @memberof MessageStamps
     */
    bad_count: any;
    /**
     * 
     * @type {number}
     * @memberof MessageStamps
     */
    laugh_count: any;
    /**
     * 
     * @type {number}
     * @memberof MessageStamps
     */
    hooray_count: any;
    /**
     * 
     * @type {number}
     * @memberof MessageStamps
     */
    confused_count: any;
    /**
     * 
     * @type {number}
     * @memberof MessageStamps
     */
    heart_count: any;
    /**
     * 
     * @type {number}
     * @memberof MessageStamps
     */
    rocket_count: any;
    /**
     * 
     * @type {number}
     * @memberof MessageStamps
     */
    eyes_count: any;
}
