/* tslint:disable */
/* eslint-disable */
/**
 * Skillme API Document
 * This is a Skillme API Document.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hirokikondo86@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Message sent by member
 * @export
 * @interface Message
 */
export interface Message {
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    url: any;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    text: any | null;
    /**
     * 
     * @type {MessageStamps}
     * @memberof Message
     */
    stamps: any;
    /**
     * 
     * @type {Date}
     * @memberof Message
     */
    created_at: any;
    /**
     * 
     * @type {Date}
     * @memberof Message
     */
    updated_at: any;
}
