/* tslint:disable */
/* eslint-disable */
/**
 * Skillme API Document
 * This is a Skillme API Document.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hirokikondo86@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Statmp member got
 * @export
 * @interface Stamp
 */
export interface Stamp {
    /**
     * 
     * @type {number}
     * @memberof Stamp
     */
    design?: any;
    /**
     * 
     * @type {number}
     * @memberof Stamp
     */
    implementation?: any;
    /**
     * 
     * @type {number}
     * @memberof Stamp
     */
    communication?: any;
}
