/* tslint:disable */
/* eslint-disable */
/**
 * Skillme API Document
 * This is a Skillme API Document.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hirokikondo86@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ThreadStamps
 */
export interface ThreadStamps {
    /**
     * 
     * @type {number}
     * @memberof ThreadStamps
     */
    good: any;
    /**
     * 
     * @type {number}
     * @memberof ThreadStamps
     */
    bad: any;
    /**
     * 
     * @type {number}
     * @memberof ThreadStamps
     */
    laugh: any;
    /**
     * 
     * @type {number}
     * @memberof ThreadStamps
     */
    hooray: any;
    /**
     * 
     * @type {number}
     * @memberof ThreadStamps
     */
    confused: any;
    /**
     * 
     * @type {number}
     * @memberof ThreadStamps
     */
    heart: any;
    /**
     * 
     * @type {number}
     * @memberof ThreadStamps
     */
    rocket: any;
    /**
     * 
     * @type {number}
     * @memberof ThreadStamps
     */
    eyes: any;
}
